### ISSUE TITLE
not listed Swiss public CAs

### ISSUE THREAD

**Issue by simonkramer** [SSLMate/caa_helper#1]
Hi,

The following two Swiss public CAs 

Swisscom: http://www.swissdigicert.ch/sdcs/portal/page
SwissSign: https://www.swisssign.com

are not (but should be) listed at

https://sslmate.com/labs/caa/

Thanks and best regards,

Simon

**Comment by robert-scheck** [comment]
As per http://repository.swisssign.com/SwissSign-Gold-CP-CPS.pdf, SwissSign does not really support CAA. Not sure, but the second sentence sounds somehow funny…does it mean that I need to make SwissSign aware about a CAA record myself?

> CAA (Certification Authority Authorization) Records
> SwissSign will not check CAA Records. If alerted to the presence of a CAA record, SwissSign will
implement an additional verification for the privilege of the Applicant to perform the certificate
request.

**Comment by AGWA** [comment]
SwissSign is now listed along with all other SSL CAs in the Mozilla program.

Swisscom is only trusted by Mozlla for email, so CAA isn't applicable.
