### ISSUE TITLE
UKFast doesn't support CAA

### ISSUE THREAD

**Issue by lurch** [SSLMate/caa_helper#101]
I sent them a support request, and they replied "I have spoken to our R&D team and there is no schedule as to when or if this will be implemented at this point in time."

**Comment by AGWA** [comment]
Looks like they support CAA now per https://docs.ukfast.co.uk/Domains/safedns/recordtypes.html?  @lurch, could you confirm?

**Comment by binbashbosh** [comment]
@lurch @AGWA

UKFast's SafeDNS does support CAA records. To implement a CAA record for your DNS Zone within SafeDNS follow the below steps:

- 1. Click on "SafeDNS" on your MyUKFast Menu
- 2. Click on "View Zones"
- 3. Click on the zone you wish to add the CAA record within
- 4. Click "Add New Record Type"
- 5. Click "Add CAA Record"

From there, you can enter the CAA Record manually in the provided text boxes.
Alternatively, you can use the SafeDNS CAA Wizard which will generate the CAA Record based on your selected certificate authorities and defined options

**Comment by AGWA** [comment]
thanks for confirming @binbashbosh !
