### ISSUE TITLE
123-reg does not support CAA

### ISSUE THREAD

**Issue by QasimK** [SSLMate/caa_helper#109]
I have an account with https://www.123-reg.co.uk/ and they do not support CAA. The last I spoke with them, they had no timeline to add it.

**Comment by hexydec** [comment]
They do support it now.

**Comment by AGWA** [comment]
Do you have a source for that by chance? Their documentation (https://www.123-reg.co.uk/support/domains/domain-name-server-dns-management-guide/) doesn't mention it. Thanks!

**Comment by hexydec** [comment]
Yeah I logged in and the CAA record type is available in the DNS section, they have some controls to enter each value and it completes the record underneath. Or you can just enter it there.![Screenshot_20250504-163038.png](https://github.com/user-attachments/assets/d2a63b71-6984-4556-b5eb-db5227b15943)

**Comment by AGWA** [comment]
Thanks for that! I've updated the support page
