### ISSUE TITLE
Opalstack now supports CAA records

### ISSUE THREAD

**Issue by composerjk** [SSLMate/caa_helper#133]
[Opalstack](https://opalstack.com/) now supports basic CAA records, allowing:

- tags: issue, issuewild, and iodef.
- supporting ";" value for no issuance.

They're currently missing support of random tag values. I've mentioned that missing detail.

I requested CAA support on Opalstack a while back. One of their support folk notified me of the availability on 8 Jan 2022. They quickly fixed a couple issues for the CAA value not supporting ";" and parameters; it now properly does. So, hopefully, they'll allow other tags, soon.

It's not yet listed in their documentation, but is available in their pull-down, using the format listed in the generic hosted DNS server CAA values. 
https://docs.opalstack.com/user-guide/domains/#adding-dns-records-manually

<img width="324" alt="CAA add DNS record dialog" src="https://user-images.githubusercontent.com/3038883/148837230-92e35352-2d5d-4135-886b-03dab4f90acc.png">

Also verified that Cert Spotter noticed the CAA records.

**Comment by AGWA** [comment]
Thanks for the report!  Opalstack is now listed.
