### ISSUE TITLE
WoSign supports CAA

### ISSUE THREAD

**Issue by PHPGangsta** [SSLMate/caa_helper#2]
As far as I can see since January 2016, see 4.2.4:
https://www.wosign.com/policy/wosign-policy-1-2-15.pdf

**Comment by AGWA** [comment]
Thanks!  Do you know what domain name they use for their CAA record by any chance?  Is it just `wosign.com`?

**Comment by PHPGangsta** [comment]
No, sorry, I don't know their issuer name. I asked WoSign via Live Chat, but nobody answered yet.
