### ISSUE TITLE
Massive increase in list of CAs checking CAA records

### ISSUE THREAD

**Issue by da2x** [SSLMate/caa_helper#25]
By September 2017, the [51 CA/Browser Forum members](https://cabforum.org/members/) have [agreed to mandatory checking and honouring of CAA records](https://ctrl.blog/entry/dns-caa) ([CABF ballot 187](https://cabforum.org/2017/03/08/ballot-187-make-caa-checking-mandatory/)). Many CAs sell branded variations under different domains, so the list of members will likely be longer than 41. Plus any outside CAs, of course.  This may require a redesign of the current UI as such a list may become unusable.

**Comment by AGWA** [comment]
All CAs in the Mozilla program are now included.
