### ISSUE TITLE
iodef - mail address not using URL format

### ISSUE THREAD

**Issue by ledragongirl** [SSLMate/caa_helper#27]
The iodef is suppose to take a URL, which means it should generate 'mailto:goto@company'

but in testing I see output where email was 'test' to be
----
Standard BIND Zone File
For BIND ≥9.9.6, PowerDNS ≥4.0.0, NSD ≥4.0.1, Knot DNS ≥2.2.0

example.com.	IN	CAA	0 issue ";"
example.com.	IN	CAA	0 iodef "test"

**Comment by AGWA** [comment]
Thank you for reporting this!  It is now fixed.
