### ISSUE TITLE
SimpleDNS 6 supports CAA

### ISSUE THREAD

**Issue by lssalgado1** [SSLMate/caa_helper#28]
Please add to DNS servers supporting CAA

**Comment by AGWA** [comment]
Documentation here: http://support.simpledns.com/kb/a215/new-in-simple-dns-plus-v_-6_0.aspx

**Comment by AGWA** [comment]
Thanks @lssalgado1 for the tip.  Added in 5288c0ad3d9286c245f973388df146551dadbc13
