### ISSUE TITLE
TeleSec does not support CAA

### ISSUE THREAD

**Issue by robert-scheck** [SSLMate/caa_helper#3]
As per

  * https://www.telesec.de/de/public-key-infrastruktur/support/root-zertifikate/category/59-t-telesec-globalroot-class-2?download=445:cps-t-telesec-globalroot-class-2
  * https://www.telesec.de/de/public-key-infrastruktur/support/root-zertifikate/category/60-t-telesec-globalroot-class-3?download=448:cps-t-telesec-globalroot-class-3
  * https://www.telesec.de/de/serverpass/support/downloadbereich/category/20-certification-practice-statement-cps?download=440:cp-cps-v3-0

TeleSec, the Trust Center of Deutsche Telekom AG, does not support CAA:

> 3.2.5.3 Prüfung von CAA Einträgen im DNS
> Im Rahmen der Berechtigungsprüfung wird keine Prüfung gegen CAA Einträge im DNS vorgenommen (CAA Records for Fully Qualified Domain Names).

**Comment by AGWA** [comment]
Closed by 4ba8dbe76efd9148e1982cc197ada228ce8332bc
