### ISSUE TITLE
Google Domains is not supported

### ISSUE THREAD

**Issue by daddavidw** [SSLMate/caa_helper#33]
Minor doc issue. Your list says that "Google Cloud DNS" is supported (which is likely true). BUT, "Google Domains (custom DNS records)" is not supported (I just learned by IMing with one of their support people). It is a different service they offer, and perhaps obvious to others, but I think it would help others avoid the confusion I had if you listed both, one supported, one not. (The support person said he did not know if or when it would be). 
Thanks.

**Comment by Ayesh** [comment]
Google Domains nowhere mentions their DNS offering as "Google Cloud DNS". I had the same question and emailed them. It's not just CAA records, but there is a whole bunch of RRs Google Domains DNS does not support, but the Cloud DNS product does.

**Comment by daddavidw** [comment]
I've love to know the other RR's they do not support. :) But, this but bug isn't really about that. To be clear, I am talking about the "document" at https://sslmate.com/labs/caa/
When I saw "Google Cloud DNS" there, in my naivete I assumed "Google Domains" too.

**Comment by Ayesh** [comment]
Right. What I was trying to say that Google Cloud DNS and Google Domains DNS are fundamentally different products. It's not that Google offers the same service, but make CAA records exclusive for Cloud DNS. I get your point one might interpret the document as both products are the same.

**Comment by AGWA** [comment]
I suppose this could confuse people, so I added a note that Google Cloud DNS is not the same as Google Domains.

**Comment by dougba** [comment]
CAA is currently a resource record type available in Google Domains.
