### ISSUE TITLE
CACert not validating?

### ISSUE THREAD

**Issue by romanf** [SSLMate/caa_helper#34]
I managed to create a valid certificate from CACert.org even though the CAA is set to Let's Encrypt (and they issued a cert before I tried CACert).

Does that mean that CACert is not following CAA?

Tests done using https://www.romanf.ch/

**Comment by AGWA** [comment]
You'd have to ask them, but I would assume not.  Their CPS doesn't say.

**Comment by romanf** [comment]
But shouldn't it be listed on https://sslmate.com/labs/caa/ then?
