### ISSUE TITLE
Add Buypass CA

### ISSUE THREAD

**Issue by runes83** [SSLMate/caa_helper#36]
The Norwegian Ca Buypass is missing.

**Comment by AGWA** [comment]
CPS here: https://www.buypass.com/support/download-center#ca-documentation

**Comment by mannyamorim** [comment]
Their certificate policy statement seems to state that they do not check CAA records

**Comment by MadZeg** [comment]
That's correct, Buypass do not check CAA records at the moment. However, we will do this by end of august and use buypass.com and buypass.no as identifiers. 

Is there any thing we could do to ensure that we are added to this list when this is done?

**Comment by AGWA** [comment]
@MadZeg Thank you for chiming in here.  On the 8th of September I am going to do a massive update and add all the CAs in the Mozilla program, including Buypass.  If Buypass starts checking CAA before that date, just add another comment here and I will be happy to add Buypass earlier.

**Comment by AGWA** [comment]
Buypass is now listed along with all other CAs in the Mozilla program.
