### ISSUE TITLE
Symantec wildcard checkbox is broken

### ISSUE THREAD

**Issue by dragongeek** [SSLMate/caa_helper#37]
When I click other providers wildcard checkbox, it adds the wildcard entry, but clicking Symantec it removes any wildcard entries, even for other organizations. (I clicked both with and without wildcard for Symantec and Digicert in my test).  I'm particularly interested in the RFC 3597 syntax, since I need both, but that is unreadable to me.

**Comment by AGWA** [comment]
Hi @dragongeek, I am unable to reproduce this.

Note that if the set of wildcard CAs matches the set of non-wlldcard CAs exactly, then the CAA spec allows the `issuewild` property to be omitted (instead, the `issue` properties will be consulted for wildcard issuance).  Is this the behavior you were seeing?

**Comment by dragongeek** [comment]
Only if I just had Symantec checked. If I check both symantec and digicert, all boxes, only symantec shows up with an issue and issuewild. digicert does not show up with an issue statement.

**Comment by AGWA** [comment]
I'm having trouble following which boxes you are checking.  Could you provide a screenshot of the page so I can tell for sure?  Also, what browser are you using?

**Comment by dragongeek** [comment]
![checked_settings](https://cloud.githubusercontent.com/assets/3876316/25585064/a43b1222-2e4d-11e7-8404-6186cdc4db2e.png)

**Comment by dragongeek** [comment]
I don't know if something was updated, but today when I check all the boxes, as in above image, the output is consistent. Problem appears to be solved.
![output_today](https://cloud.githubusercontent.com/assets/3876316/25585150/1f9086c8-2e4e-11e7-8527-ecff113cb2c7.png)
