### ISSUE TITLE
German CA "D-Trust - Bundesdruckerei" missing

### ISSUE THREAD

**Issue by robert-scheck** [SSLMate/caa_helper#4]
The German CA "D-Trust - Bundesdruckerei" is missing, however I was not able to figure out whether they support CAA or not, but I sent them a request and asked for clarification.

**Comment by robert-scheck** [comment]
According to the reply of D-Trust with ticket *ID#24-1657421, CAA tags are not handled.

**Comment by AGWA** [comment]
Added in d0e92dbed0da5b48d80e129d3a3396914570fbc0
