### ISSUE TITLE
Please add Actalis to the list of CAs

### ISSUE THREAD

**Issue by defacto64** [SSLMate/caa_helper#47]
Please add Actalis to the list of available CAs of your nice CAA record generator.
Actalis is identified by "**actalis.it**"

Thank you,
Adriano Santoni
ACTALIS S.p.A.
www.actalis.it

**Comment by AGWA** [comment]
Per their CPS, Actalis will begin checking CAA no later than Sep 8, 2017.

**Comment by AGWA** [comment]
Actalis is now listed along with all other CAs in the Mozilla program.

**Comment by defacto64** [comment]
Thank you.
Adriano


Il 31/Ago/2017 18:21, "Andrew Ayer" <notifications@github.com> ha scritto:
