### ISSUE TITLE
Add domeneshop / domainnameshop as DNS provider with CAA

### ISSUE THREAD

**Issue by byeskille** [SSLMate/caa_helper#49]
Today I got an update on the CAA support for DNS services from the Norwegian company Domeneshop / Domainnameshop
[https://www.domeneshop.no/](https://www.domeneshop.no/)
[https://domainnameshop.com/?currency=GBP&lang=en](https://domainnameshop.com/?currency=GBP&lang=en)

I can't find any public announcement, but I have tested it for my domain byeskille.no and it seems to work
[https://www.ssllabs.com/ssltest/analyze.html?d=byeskille.no&s=188.166.11.188](https://www.ssllabs.com/ssltest/analyze.html?d=byeskille.no&s=188.166.11.188)

**Comment by AGWA** [comment]
Added, thanks @byeskille !
