### ISSUE TITLE
Flag spefication

### ISSUE THREAD

**Issue by maurice123m** [SSLMate/caa_helper#50]
At this moment the generator only uses the 0 as a flag value. Would it be possible to also include 128 in the generator as a valid flag value?

**Comment by AGWA** [comment]
Why?  As I explained in #23, setting the critical flag is not necessary and has the potential to cause confusion.

**Comment by maurice123m** [comment]
The generator is really easy to understand so I think adding the option to specify the flag would not cause any confusion
