### ISSUE TITLE
CloudFlare CAA is now Available

### ISSUE THREAD

**Issue by ahaw021** [SSLMate/caa_helper#51]
Now out of beta

![image](https://user-images.githubusercontent.com/26753809/28299898-39a15ebe-6bae-11e7-9b36-075dd2e65cd2.png)

Andrei

**Comment by Starbix** [comment]
It's still in beta, you need to contact support to be able to use CAA records

**Comment by AGWA** [comment]
documentation confirms it is still in beta: https://support.cloudflare.com/hc/en-us/articles/115000310792-Configuring-CAA-Records-

**Comment by Starbix** [comment]
I signed up for the beta, works flawlessly
