### ISSUE TITLE
QuoVadis CAA record 

### ISSUE THREAD

**Issue by weddi-eddy** [SSLMate/caa_helper#58]
QuoVadis will be using 'quovadisglobal.com' as their value for CAA records.  You can find more information at [https://support.quovadisglobal.com/kb/a481/certification-authority-authorisation-caa.aspx](https://support.quovadisglobal.com/kb/a481/certification-authority-authorisation-caa.aspx).

`example.com.        CAA    0     issue "quovadisglobal.com"`
`example.com.        CAA    0     issuewild "quovadisglobal.com"`
`example.com.        CAA    0     iodef "mailto:cert-admin@example.com"`

Would you be able to add us as an option to the CAA Record Generator please?

**Comment by AGWA** [comment]
Yes, once your CPS is updated to reflect CAA support, I will add QuoVadis.

**Comment by weddi-eddy** [comment]
Perfect! I will get it updated and update this issue when completed.  Thank you.

**Comment by AGWA** [comment]
QuoVadis is now listed along with all other CAs in the Mozilla program.
