### ISSUE TITLE
Certum does not support CAA

### ISSUE THREAD

**Issue by robert-scheck** [SSLMate/caa_helper#6]
As per http://www.certum.eu/servlet/pl.id.sys.servlets.FileDownloadServlet?filename=/upload_module/wysiwyg/certum/cert_doc/cps/nonqualified/CCP-DK02-ZK02_Certification_Practice_Statement_of_CERTUM_Certification_Services_v4.2_valid.pdf the Certum Trusted Network CA does not support CAA:

> 4.2.4. Certificate Authority Authorization Records Processing
> CERTUM does not search for Certification Authority Authorization (CAA) DNS resource records when issuing subscribers’ certificates.

**Comment by AGWA** [comment]
Closed by f485173
