### ISSUE TITLE
comodoca.com instead of comodo.com?

### ISSUE THREAD

**Issue by danielcompton** [SSLMate/caa_helper#68]
Looking at this support document it seems like it should be comodoca.com?

https://support.comodo.com/index.php?/Knowledgebase/Article/View/1204/1/caa-record---certification-authority-authorization

**Comment by AGWA** [comment]
Hi @danielcompton, Comodo also accepts comodo.com and it is listed first in the Mozilla report from which this tool gets its data: https://ccadb-public.secure.force.com/mozilla/CAInformationReport
