### ISSUE TITLE
Add Vultr to DNS providers

### ISSUE THREAD

**Issue by Ayesh** [SSLMate/caa_helper#70]
My VPS host, Vultr.com now supports CAA records as well. Can we add it to the DNS providers list, please?

![vultr](https://user-images.githubusercontent.com/811553/30359202-bb3d72a2-9866-11e7-9a23-a27160d9aaf6.png)

Thanks!

**Comment by AGWA** [comment]
Thanks, added in 24939735c582daa9fec2d1f3cd2825c76d2feb15
