### ISSUE TITLE
Using rapidssl.com for RapidSSL

### ISSUE THREAD

**Issue by jhed9** [SSLMate/caa_helper#75]
RapidSSL requests "rapidssl.com" be in CAA records when purchasing certificates. caa_helper currently generates a record for them using "symantec.com"

https://knowledge.rapidssl.com/support/ssl-certificate-support/index?page=content&id=SO28449

**Comment by AGWA** [comment]
Symantec and RapidSSL are the same.  See #48 for details.

**Comment by jhed9** [comment]
You're right, either symantec.com or rapidssl.com in the CAA record will work for purchasing at rapidssl.com. That sure is confusing. Sorry for the dup issue.
