### ISSUE TITLE
Google Domains DNS now supports CAA

### ISSUE THREAD

**Issue by kerzyte** [SSLMate/caa_helper#81]

**Comment by tbehling** [comment]
I can confirm Google Domains does now support CAA records.

**Comment by DrMattChristian** [comment]
I can confirm that domain names hosted at googledomains.com now supports CAA. Google Domains' [resource records documentation](https://support.google.com/domains/answer/3251147) does not mention CAA yet. However you can use the Google Domains' [DNS settings](https://support.google.com/domains/answer/3290350) to add a custom resource record with CAA type. Supports multi-part CAA records as well, such as iodef, multiple issue entries, etc.

**Comment by Ayesh** [comment]
Finally 👍

**Comment by AGWA** [comment]
Thanks everyone for the confirmations.  Google Domains DNS is now listed as supported.
