### ISSUE TITLE
Dreamhost does not support CAA records

### ISSUE THREAD

**Issue by aaronssh** [SSLMate/caa_helper#82]
As of 10/24/2017, Dreamhost still does not support CAA records

**Comment by sa7mon** [comment]
Still true as of 12/19/17: https://twitter.com/DreamHostCare/status/943139095802458112

**Comment by AGWA** [comment]
forum discussion: https://discussion.dreamhost.com/t/allow-caa-records-in-dhs-dns/64170

**Comment by AGWA** [comment]
Thank you @aaronssh and @sa7mon for the info. Dreamhost is now listed as not supporting CAA.
