### ISSUE TITLE
Enom/Tucows DNS do not support CAA

### ISSUE THREAD

**Issue by DrMattChristian** [SSLMate/caa_helper#83]
Domain names with [DNS hosted](https://help.enom.com/hc/en-us/articles/115000486451-Nameservers-DNS-) at [enom.com](https://www.enom.com/) ([now owned by Tucows](https://www.enom.com/blog/enom-3-months-tucows-acquisition/)) do not support the CAA record type.

I asked Enom support back in Aug 2017 and Enom support replied:

> My apologies but I have checked with my seniors and have been able to establish that we do not support and do not plan to support CAA DNS host records.
> 
> If you require CAA record types you may open a free account with another DNS hosting company such as cloudflare which offers the CAA record type but you will need to move over all of your current host records to cloudflare and point your nameservers for your domain to the nameservers that cloudflare provides.

**Comment by AGWA** [comment]
Thanks @DrMattChristian - Enom/Tucows is now listed
