### ISSUE TITLE
CAA support: Host Europe, Lima-City, netcup, UD Media

### ISSUE THREAD

**Issue by ASMag** [SSLMate/caa_helper#84]
Host Europe, Lima-City and netcup do not support CAA records.
UD Media supports CAA records.

Maybe this information is relevant to https://sslmate.com/caa/support

**Comment by ASMag** [comment]
An evidence for UD Media's CAA support you can find here in their german changelog of March 2017
"Domains: DNS-Einstellungen: CAA-Einträge nun möglich" (Translation: Domains: DNS settings: CAA entries now possible)
https://www.udmedia.de/newsletter/changelog.txt

**Comment by AGWA** [comment]
Thank you for the info! UD Media is now listed as of 8be68fd298a3083a30ed734879d47ee2ba447bac
