### ISSUE TITLE
rackspace / rackspace.com does not support caa

### ISSUE THREAD

**Issue by ryantig** [SSLMate/caa_helper#86]
Rackspace / rackspace.com "Cloud DNS" (dns for hosted domains) does not support CAA
They only support:

Type | Type id
:------: | :------:
A | 1
AAAA | 28
CNAME | 5
MX | 15
NS | 2
SRV | 33
TXT | 16

**Comment by AGWA** [comment]
https://developer.rackspace.com/docs/cloud-dns/v1/general-api-info/supported-record-types/ does not list CAA

**Comment by AGWA** [comment]
Thank you @ryantig for the tip. Rackspace is now listed as not supporting CAA.
